### ISSUE TITLE
Refine geometry from AgBehenate run

### ISSUE THREAD

**Issue by fredericpoitevin** [lcls-users/btx#15]
At the moment `geom_opt` finds the detector distance.

New features to add:
- find center
- refine individual panel geometries (requires adding some logic for area detector geometry refinement)

**Comment by carbonscott** [comment]
This solution might facilitate finding beam centers.  The idea is to fit a circle to one of the Ag Behenate rings by refining a ballpark circle created from three clicks on an Ag Behnate image.  A demo can be checked out with this link [https://github.com/carbonscott/spatial-calib-xray](https://github.com/carbonscott/spatial-calib-xray).

**Comment by apeck12** [comment]
Currently we only update the z-distance in the output geom file, but we need to update the center as well. Below lines give a sense for how to accomplish that: https://github.com/lcls-psana/psocake/blob/bcbc0b7a6715186cf78519f5585447d6e4c476ee/psocake/DiffractionGeometryPanel.py#L538

**Comment by carbonscott** [comment]
Thanks Ariana.  It looks that the center position is retrieved from the ROI widget according to the following line of code.  
```
dx = self.parent.pixelSize * 1e6 * (self.parent.roi.centreX - self.parent.cx)  # microns
```
Specifically, I remember it's the circular widget that we used during the beamtime last week.  

For a more seamless `btx` experience,  it might be good idea to integrate the three-click beam finding into the workflow.  Do you think if it's the way to go, @fredericpoitevin @apeck12?  If so, could you also advise how or where it can be integrated?  Thanks.

**Comment by apeck12** [comment]
@carbonscott, our aim has been to create a fully automated pipeline, though we've been discussing that it'd also be nice to offer some interactive features (that ideally the pipeline wouldn't depend on) as well. The [`AgBehenate` class](https://github.com/lcls-users/btx/blob/main/btx/diagnostics/ag_behenate.py) estimates the distance to the detector based on (1) finding peaks in the powder and then (2) determining the detector distance at which these powder peaks are equidistant in q-space. 

Since this class finds the radial positions of the rings (`peaks_predicted` and `peaks_observed` in the `opt_distance` function), I wonder if we could use that instead of manually-identified positions as a starting point for the centering search? So at the end we might have an `opt_geom` function in this class that iteratively performs the current `opt_distance` followed by `opt_center` based on your code to refine the overall geometry.

**Comment by carbonscott** [comment]
@apeck12 Thanks for your explanation.  The iterative routine should make the user experience more seamless.  I wonder if there is an existing script that optimizes detector distance from an Ag Behenate scattering image.  Then, I'll look into integrating beam center optimization into the current workflow.

**Comment by apeck12** [comment]
@carbonscott, thanks for looking into that. We already have a script to optimize the detector distance from a silver behenate powder; you can find it here: https://github.com/lcls-users/btx/blob/main/btx/diagnostics/ag_behenate.py.

**Comment by carbonscott** [comment]
@apeck12 Thanks.  Do I run it like `$ . elog_submit.sh -c ../tutorial/mfxlv4920.yaml -t opt_distance -n 1`?  I just found this example from [the tutorial](https://github.com/lcls-users/btx/wiki/Tutorial).

**Comment by fredericpoitevin** [comment]
Thanks @carbonscott for looking into this.

As @apeck12 explained above, the desired workflow would be:
1. Roughly find the rings with current center using existing approach.
2. Refine those rings by updating center and radius using e.g. lmfit, as implemented in your interactive tool
3. Deploy resulting geometry with updated center and detector distance.

I don't think an interactive tool is compatible with btx, *but* it would be great to see how your standalone tool could be used by the beamline scientists during beamtime if they desired. We can talk about that :)

**Comment by carbonscott** [comment]
@fredericpoitevin @apeck12 This PR is intended to provide a demo for the new feature.  Can you try it on your end without merging?  Let me know if there is a better way for provide a demo.  

If this feature looks good, I can integrate the `spatial-calib-xray` directly into btx.  Furthermore, I can replace the interactive visualization with a static pdf or png file.
