### ISSUE TITLE
Show peakograms as a function of transmission using runs 198-214.

### ISSUE THREAD

**Issue by fredericpoitevin** [lcls-users/btx#160]

**Comment by apeck12** [comment]
During stream analysis, runs were consolidated according to their transmission. Peakograms as a function of increasing transmission are shown below. There was a noticeable drop in indexing rates at lower transmission, presumably because the peaks are lost in the background. So although 4-5 runs were collected at 1%, 5%, and 100% transmission each, there are significantly more indexable crystals at 100% tranmission.

**1% transmission**: runs 200, 201, 206-208
![peakogram_sample1t](https://user-images.githubusercontent.com/6363287/182007363-76408330-f542-4abb-96e5-d66ac70820c0.png)
**5% transmission**: runs 211-214
![peakogram_sample5t](https://user-images.githubusercontent.com/6363287/182007364-53a4e774-5c31-4a9e-b077-51d9c4edeebd.png)
**9% transmission**: run 210
![peakogram_sample9t](https://user-images.githubusercontent.com/6363287/182007365-ee303d35-1aa3-4e2c-8183-dc2d6bcabf4b.png)
**10% transmission**: runs 199, 202
![peakogram_sample10t](https://user-images.githubusercontent.com/6363287/182007366-9732b7b7-ae3b-430f-8e90-cf261988c1ea.png)
**50% transmission**: run 209
![peakogram_sample50t](https://user-images.githubusercontent.com/6363287/182007368-2a515481-e20e-4df3-81d9-27ba62f260a4.png)
**100% transmission**: runs 198, 203-205
![peakogram_sample100t](https://user-images.githubusercontent.com/6363287/182007369-bd182228-2b3a-41b3-b7aa-db39938b4463.png)
